<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TestResourceType.aspx.cs" Inherits="WebApplication1.TestResourceType" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:TextBox ID="null" runat="server" />

        <p>Resource Type: </p>
        <table>
            <tr>
                <td colspan ="2">
                    <asp:GridView ID ="Listing" runat="server" DataKeyNames="Name,IsActive"
                        AutoGenerateDeleteButton="True" 
                        onrowdeleting="Listing_RowDeleting" OnSelectedIndexChanged="Listing_SelectedIndexChanged"></asp:GridView>
                </td>
            </tr>
        </table>
    
        <ul id="one">
            <li> </li>
	    </ul>
    </form> 
</body>
</html>